# Generated by Django 5.2.6 on 2025-09-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
    ]
